// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_rCZ1tNq3t_rwVxDC596-BjTMOtXS14',
    appId: '1:201219973439:web:e0b8dc51b04197eee1f38a',
    messagingSenderId: '201219973439',
    projectId: 'charify-328c3',
    authDomain: 'charify-328c3.firebaseapp.com',
    storageBucket: 'charify-328c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6BzU4gZKnr15vXQDKTlolAorsgtsgzcs',
    appId: '1:201219973439:android:f417efcfaeed6f28e1f38a',
    messagingSenderId: '201219973439',
    projectId: 'charify-328c3',
    storageBucket: 'charify-328c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHJbqShgk4i69RXL52iDOZH5sGP2W8KwI',
    appId: '1:201219973439:ios:10112b511e825b1ae1f38a',
    messagingSenderId: '201219973439',
    projectId: 'charify-328c3',
    storageBucket: 'charify-328c3.firebasestorage.app',
    iosClientId: '201219973439-1baajafb4lqfv33b0hd662vsh030h2hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.charify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHJbqShgk4i69RXL52iDOZH5sGP2W8KwI',
    appId: '1:201219973439:ios:10112b511e825b1ae1f38a',
    messagingSenderId: '201219973439',
    projectId: 'charify-328c3',
    storageBucket: 'charify-328c3.firebasestorage.app',
    iosClientId: '201219973439-1baajafb4lqfv33b0hd662vsh030h2hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.charify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6_rCZ1tNq3t_rwVxDC596-BjTMOtXS14',
    appId: '1:201219973439:web:f9e68b946679f933e1f38a',
    messagingSenderId: '201219973439',
    projectId: 'charify-328c3',
    authDomain: 'charify-328c3.firebaseapp.com',
    storageBucket: 'charify-328c3.firebasestorage.app',
  );
}
